--- # ERROR Handling
- hosts: app
  user: root
  connection: ssh
  gather_facts: no
  tasks: 
    - name: Execute a command that will fail
      command: /bin/sl
      ignore_errors: yes
    - name: Installing the Software
      yum:  pkg=nmap state=latest
