--- # Mount Workout
- hosts: app
  user: root
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: mount the remote device
      mount: name=/mnt/tmp src=/dev/sdb1 fstype=ext3 opts=rw state=present
