--- # Raw 
- hosts: app
  remote_user:  root
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  tasks:
    - name: Find the System uptime for the host above
      raw:  /usr/bin/uname > uname.log
      args:
       executable: /bin/bash

