--- # AWS EC2
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/key.yml
  tasks:
  - name: Basic Provisioning of an AMI from our Instance
    ec2_group:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      name: MyTestLinuxAcademy
      description: This is the EC2 Group Demo
      vpc_id: vpc-1db46f7b
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0

