--- # AWS EC2
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/key.yml
  tasks:
  - name: Basic Provisioning of an AMI from our Instance
    ec2_vol:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance: i-029013a77588881ef
      state: list
    register: snapshot
  - debug: msg={{ snapshot }}
