--- # AWS EC2
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/key.yml
  tasks:
  - name: Basic Provisioning of an AMI from our Instance
    ec2_ami:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      instance_id: i-029013a77588881ef
      wait: no
      name: yournameAMI2
      tags:
         Name: MyNewAMI2
         Service: TestAMIService2
      device_mapping:
       - device_name: /dev/sdb1
         size: 100
         delete_on_termination: true
         volume_type: gp2
    register: instance
