--- # AWS EC2
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/key.yml
  tasks:
  - name: Basic Provisioning of an AMI from our Instance
    ec2_ami_copy:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      source_region: "{{ aws_region }}"
      region: us-east-1
      source_image_id: ami-733b740b
      wait: no
      name: nameAMI2
      tags:
         Name: MyNwAMI2
         Service: TstAMIService2
    register: instance
