--- # AWS EC2
- hosts: aws
  remote_user: ec2-user
  become_method: sudo
  gather_facts: yes
  connection: ssh
  tasks:
  - name:  Execute a Shell Command for listing the directory
    shell: ls -al /tmp
    register: result
  - name: Display the results in JSON format
    debug: var=result
