--- # This is our Ansible playbook
- hosts: app
  user:  root
  sudo: yes       
  connection: ssh 
  gather_facts: no
  vars:
     playbook_version: 0.1b
     vars_files:
       - conf/unique.yml
       - conf/webroot.yml
  vars_prompt:
    - name: web_domain
      prompt: Web DominS
  tasks:
    - name: Check System HW State
      command: uptime 
#      check_mode: yes
