--- # Setting up Handler
- hosts: app
  user: root
  sudo: yes
  connection: ssh
  gather_facts: no
  vars:
    playbook_version: 1.12
  vars_prompt:
    - name: Web_World
      prompt: My World
  tasks:
    - name: Install Web Server
      action: yum name=telnet state=present
